[versions]
androidx-compose-bom="2024.06.00"
androidx-activity-compose = "1.9.0"

[libraries]

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }